### PR TITLE
[OP] Gelu

### PR DESCRIPTION
**Pull request by anadeem2**
## Description ##
Lower gelu operator to raf gelu instead of decomposing into smaller. 

## Checklist ##

- [x] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [x] Changes are complete (i.e. I finished coding on this PR)
- [ ] Code is well-documented
- [ ] All changes have test coverage

cc @awslabs/raf-reviewer @zachzzc

### CODE REVIEW

**Review by comaniac — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
Ah wait, do we need `InferGelu`?

**Comment by anadeem2** [comment]
GELU is generic OP so its shape is just input.

**Review by zachzzc — APPROVED** [review]
LGTM

**Comment by comaniac** [comment]
Please resolve the conflict and we could merge this.

**Comment by comaniac** [comment]
Thanks @anadeem2 @zachzzc

**Pull request merged**
